### ISSUE TITLE
Arrow Keys and Tab not working

### ISSUE THREAD

**Issue by mms-hamburg** [bobthecow/psysh#224]
Somehow i cant use the arrow keys to navigation in my php lines within psysh.

i always get stuff like this:  ^[[D

Any suggestions?  Using /bin/bash

**Comment by GrahamCampbell** [comment]
DO you have all the extensions installed.

**Comment by GrahamCampbell** [comment]
Where there any dependencies "suggested" when you ran composer install?

**Comment by mms-hamburg** [comment]
fixed it running php5-readline.

thanks!

**Comment by ezmiller** [comment]
What can I run on  Mac, where apt-get isn't available. I looked for php5-readline in brew, but it's not there.

**Comment by veah** [comment]
same problem as the upstair

At the begining I installed psysh using composer on my mac,and I found out I can't use the arrow keys in Psy because those keys print out the ^[[D or ^[[A things
Then I installed psysh through homebrew on my mac,and the output of installation showed that there is a dependency named 'readline' installed.But I still can't use the arrow keys

**Comment by bobthecow** [comment]
What does `Psy\info()` say?

**Comment by veah** [comment]
this is the Psy\info(), I think it means the readline still doesn't work well?
```
>>> Psy\info()
=> [
     "PsySH version" => "v0.8.2",
     "PHP version" => "5.6.24",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.8.2",
       "update check interval" => "weekly",
       "update cache file" => "/Users/veah-mac/.config/psysh/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => true,
       "posix available" => true,
     ],
     "readline" => [
       "readline available" => false,
     ],
     "history" => [
       "history file" => "/Users/veah-mac/.config/psysh/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => false,
       "custom matchers" => [],
     ],
   ]
```

**Comment by bobthecow** [comment]
Yeah, it looks a lot like something's not working with your readline.

That PHP version looks a lot like a version that ships with OS X, not like one installed via Homebrew. What does `which -a php` say?

**Comment by veah** [comment]
that's it: 
```
/Applications/XAMPP/xamppfiles/bin/php
/usr/local/bin/php
/usr/bin/php
```

**Comment by veah** [comment]
sorry I dont understand...what do you mean?

**Comment by bobthecow** [comment]
The PHP version installed via XAMPP (`/Applications/XAMPP/xamppfiles/bin/php`) is being used when you run psysh, not the version from Homebrew (`/usr/local/bin/php`). So even though the Homebrew installed PHP came with readline, you're not getting it in your psysh sessions.

Change your $PATH so that `/usr/local/bin` comes before XAMPP's `bin` and you'll be fine :)

**Comment by veah** [comment]
Great! That works!
